/**
 * Offline submission template (.xlsx) generated from FIELD_DEFS.
 * Sheets: Meta (template marker + version) · Data (header row) · Field guide.
 */
import ExcelJS from "exceljs";

import { FIELD_DEFS, MGR_TEMPLATE_NAME, MGR_TEMPLATE_VERSION } from "@/lib/mgr-fields";

export const META_SHEET = "Meta";
export const DATA_SHEET = "Data";
export const GUIDE_SHEET = "Field guide";

function workbook(templateVersion = MGR_TEMPLATE_VERSION): ExcelJS.Workbook {
  const wb = new ExcelJS.Workbook();
  wb.creator = "BBNJ Cl-HM prototype";
  wb.created = new Date();

  const meta = wb.addWorksheet(META_SHEET);
  meta.addRow(["template", MGR_TEMPLATE_NAME]);
  meta.addRow(["templateVersion", templateVersion]);
  meta.addRow(["generatedAt", new Date().toISOString()]);
  meta.addRow(["instructions", "Fill one row per pre-collection notification on the Data sheet. Do not rename headers. Formulas are not accepted."]);
  meta.getColumn(1).width = 18;
  meta.getColumn(2).width = 90;

  const data = wb.addWorksheet(DATA_SHEET);
  data.addRow(FIELD_DEFS.map((f) => f.excelHeader));
  data.getRow(1).font = { bold: true };
  FIELD_DEFS.forEach((f, i) => {
    data.getColumn(i + 1).width = Math.max(16, Math.min(40, f.excelHeader.length + 6));
  });
  data.views = [{ state: "frozen", ySplit: 1 }];

  const guide = wb.addWorksheet(GUIDE_SHEET);
  guide.addRow(["field", "excel_header", "required", "kind", "agreement_basis_or_implementation", "help", "allowed_values"]);
  guide.getRow(1).font = { bold: true };
  for (const f of FIELD_DEFS) {
    guide.addRow([f.key, f.excelHeader, f.required ? "yes" : "no", f.kind, f.basis, f.help, f.options ? f.options.join(" | ") : f.kind === "boolean" ? "yes | no" : ""]);
  }
  [18, 26, 10, 10, 70, 60, 30].forEach((w, i) => (guide.getColumn(i + 1).width = w));
  return wb;
}

export async function buildMgrTemplate(opts: { templateVersion?: number } = {}): Promise<Buffer> {
  const wb = workbook(opts.templateVersion);
  return Buffer.from(await wb.xlsx.writeBuffer());
}

/** Fixture used by the "Import sample" fallback and by smoke. */
export async function buildMgrSample(opts: { rows?: number; withFormula?: boolean } = {}): Promise<Buffer> {
  const wb = workbook();
  const data = wb.getWorksheet(DATA_SHEET)!;
  const n = opts.rows ?? 2;
  for (let i = 1; i <= n; i++) {
    const row: Record<string, unknown> = {
      title: `Offline cruise SAMPLE-${String(i).padStart(2, "0")}`,
      geographical_area: i % 2 ? "CCZ" : "Reykjanes Ridge",
      objectives: "Sample row generated by the prototype fixture.",
      method_means: "RV Sample (1,800 t); box corer.",
      expected_dates: "2027-01-10 to 2027-02-02",
      sponsoring_institution: "Demo Institute — Dr B. Example",
      participation_opportunities: "One berth for a scientist from a developing State.",
      data_management_plan: "https://example.org/dmp/sample",
      tk_fpic_flag: "no",
      confidentiality: "public",
    };
    data.addRow(FIELD_DEFS.map((f) => row[f.excelHeader] ?? ""));
  }
  if (opts.withFormula) {
    const r = data.addRow(FIELD_DEFS.map((f) => (f.excelHeader === "geographical_area" ? "CCZ" : f.excelHeader === "tk_fpic_flag" ? "no" : f.excelHeader === "confidentiality" ? "public" : "")));
    r.getCell(1).value = { formula: 'CONCATENATE("Formula", " row")', result: "Formula row" };
  }
  return Buffer.from(await wb.xlsx.writeBuffer());
}

export async function sheetNames(buf: Buffer | Uint8Array): Promise<string[]> {
  const wb = new ExcelJS.Workbook();
  await wb.xlsx.load(buf as unknown as ExcelJS.Buffer);
  return wb.worksheets.map((w) => w.name);
}
