/**
 * Offline submission template (.xlsx) generated from FIELD_DEFS.
 * Sheets: Meta (template marker + version) · Data (header row) · Field guide.
 */
import ExcelJS from "exceljs";

import { FIELD_DEFS, MGR_TEMPLATE_NAME, MGR_TEMPLATE_VERSION } from "@/lib/mgr-fields";

export const META_SHEET = "Meta";
export const DATA_SHEET = "Data";
export const GUIDE_SHEET = "Field guide";

function workbook(templateVersion = MGR_TEMPLATE_VERSION): ExcelJS.Workbook {
  const wb = new ExcelJS.Workbook();
  wb.creator = "BBNJ Cl-HM prototype";
  wb.created = new Date();

  const meta = wb.addWorksheet(META_SHEET);
  meta.addRow(["template", MGR_TEMPLATE_NAME]);
  meta.addRow(["templateVersion", templateVersion]);
  meta.addRow(["generatedAt", new Date().toISOString()]);
  meta.addRow(["instructions", "Fill one row per pre-collection notification on the Data sheet. Do not rename headers. Formulas are not accepted."]);
  meta.getColumn(1).width = 18;
  meta.getColumn(2).width = 90;

  const data = wb.addWorksheet(DATA_SHEET);
  data.addRow(FIELD_DEFS.map((f) => f.excelHeader));
  data.getRow(1).font = { bold: true };
  FIELD_DEFS.forEach((f, i) => {
    data.getColumn(i + 1).width = Math.max(16, Math.min(40, f.excelHeader.length + 6));
  });
  data.views = [{ state: "frozen", ySplit: 1 }];

  const guide = wb.addWorksheet(GUIDE_SHEET);
  guide.addRow(["field", "excel_header", "required", "kind", "agreement_basis_or_implementation", "help", "allowed_values"]);
  guide.getRow(1).font = { bold: true };
  for (const f of FIELD_DEFS) {
    guide.addRow([f.key, f.excelHeader, f.required ? "yes" : "no", f.kind, f.basis, f.help, f.options ? f.options.join(" | ") : f.kind === "boolean" ? "yes | no" : ""]);
  }
  [18, 26, 10, 10, 70, 60, 30].forEach((w, i) => (guide.getColumn(i + 1).width = w));
  return wb;
}

export async function buildMgrTemplate(opts: { templateVersion?: number } = {}): Promise<Buffer> {
  const wb = workbook(opts.templateVersion);
  return Buffer.from(await wb.xlsx.writeBuffer());
}

export const ERROR_COLUMN_HEADER = "Error (fix and delete this column before re-import)";

/**
 * Fixture used by the "Import sample" fallback and by smoke.
 * `withInvalid` appends one row that fails validation (missing objectives, bad
 * confidentiality value) so the closed loop — error report → fix → re-import —
 * can be demonstrated without hand-editing a workbook.
 */
export async function buildMgrSample(opts: { rows?: number; withFormula?: boolean; withInvalid?: boolean } = {}): Promise<Buffer> {
  const wb = workbook();
  const data = wb.getWorksheet(DATA_SHEET)!;
  const n = opts.rows ?? 2;
  for (let i = 1; i <= n; i++) {
    const row: Record<string, unknown> = {
      title: `Offline cruise SAMPLE-${String(i).padStart(2, "0")}`,
      geographical_area: i % 2 ? "CCZ" : "Reykjanes Ridge",
      objectives: "Sample row generated by the prototype fixture.",
      method_means: "RV Sample (1,800 t); box corer.",
      expected_dates: "2027-01-10 to 2027-02-02",
      sponsoring_institution: "Demo Institute — Dr B. Example",
      participation_opportunities: "One berth for a scientist from a developing State.",
      data_management_plan: "https://example.org/dmp/sample",
      tk_fpic_flag: "no",
      confidentiality: "public",
    };
    data.addRow(FIELD_DEFS.map((f) => row[f.excelHeader] ?? ""));
  }
  if (opts.withInvalid) {
    const bad: Record<string, unknown> = {
      title: "Offline cruise SAMPLE-INVALID (missing objectives, bad tier)",
      geographical_area: "CCZ",
      objectives: "",
      method_means: "RV Sample (1,800 t); box corer.",
      expected_dates: "2027-03-01 to 2027-03-20",
      sponsoring_institution: "Demo Institute — Dr C. Example",
      participation_opportunities: "",
      data_management_plan: "https://example.org/dmp/sample-invalid",
      tk_fpic_flag: "no",
      confidentiality: "secret",
    };
    data.addRow(FIELD_DEFS.map((f) => bad[f.excelHeader] ?? ""));
  }
  if (opts.withFormula) {
    const r = data.addRow(FIELD_DEFS.map((f) => (f.excelHeader === "geographical_area" ? "CCZ" : f.excelHeader === "tk_fpic_flag" ? "no" : f.excelHeader === "confidentiality" ? "public" : "")));
    r.getCell(1).value = { formula: 'CONCATENATE("Formula", " row")', result: "Formula row" };
  }
  return Buffer.from(await wb.xlsx.writeBuffer());
}

/**
 * Error report for one import run: the current template with the Data sheet
 * holding only the rejected rows (original values) plus a trailing Error
 * column. The submitter fixes the cells, deletes the Error column, re-imports.
 * Meta carries the source run id for traceability.
 */
export async function buildMgrErrorReport(run: {
  runId: string;
  at: string;
  rows: { row: number; ok: boolean; error?: string; values?: Record<string, string> }[];
}): Promise<Buffer> {
  const wb = workbook();
  const meta = wb.getWorksheet(META_SHEET)!;
  meta.addRow(["errorReportOf", run.runId]);
  meta.addRow(["importedAt", run.at]);
  const data = wb.getWorksheet(DATA_SHEET)!;
  const errCol = FIELD_DEFS.length + 1;
  data.getRow(1).getCell(errCol).value = ERROR_COLUMN_HEADER;
  data.getRow(1).getCell(errCol).font = { bold: true, color: { argb: "FFB00020" } };
  data.getColumn(errCol).width = 80;
  for (const r of run.rows.filter((x) => !x.ok)) {
    const cells = FIELD_DEFS.map((f) => r.values?.[f.key] ?? "");
    cells.push(`Row ${r.row}: ${r.error ?? "rejected"}`);
    data.addRow(cells);
  }
  return Buffer.from(await wb.xlsx.writeBuffer());
}

/** Test helper: drop the Error column from an error report and patch cells so it re-imports cleanly. */
export async function correctErrorReport(buf: Buffer | Uint8Array, patch: Record<string, string>): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  await wb.xlsx.load(buf as unknown as ExcelJS.Buffer);
  const data = wb.getWorksheet(DATA_SHEET)!;
  const headers: string[] = [];
  data.getRow(1).eachCell({ includeEmpty: false }, (c) => headers.push(String(c.value ?? "")));
  const errIdx = headers.indexOf(ERROR_COLUMN_HEADER);
  if (errIdx >= 0) data.spliceColumns(errIdx + 1, 1);
  data.eachRow((row, n) => {
    if (n === 1) return;
    for (const [header, value] of Object.entries(patch)) {
      const idx = FIELD_DEFS.findIndex((f) => f.excelHeader === header);
      if (idx >= 0) row.getCell(idx + 1).value = value;
    }
  });
  return Buffer.from(await wb.xlsx.writeBuffer());
}

export async function sheetNames(buf: Buffer | Uint8Array): Promise<string[]> {
  const wb = new ExcelJS.Workbook();
  await wb.xlsx.load(buf as unknown as ExcelJS.Buffer);
  return wb.worksheets.map((w) => w.name);
}
